### ISSUE TITLE
Phone number block

### ISSUE THREAD

**Issue by nickhamze** [georgestephanis/random-blocks#1]
For this one all you'd need on the backend is a simple place to input a phone number. It would be nice if it had some basic validation to make sure that when it is displayed on the front end the number is valid so it can be dialed.

On the front end the number would be displayed with the tel prefix so when they click on it on mobile it actually dials the phone number:
<a href="tel:5555555555">555.555.5555/a>

**Comment by georgestephanis** [comment]
Validation could be tricky, especially for international numbers, not all of which use the same format as us-based numbers.

Info: https://en.wikipedia.org/wiki/E.164

Probably would be able to just do a dropdown for country codes, and then based on the country code validate the following number for known formats.

**Comment by georgestephanis** [comment]
Found a handy React component that does most of this, so I just used that.

https://www.npmjs.com/package/react-phone-number-input

It's now working and in master.
