### ISSUE TITLE
Address Block

### ISSUE THREAD

**Issue by nickhamze** [georgestephanis/random-blocks#2]
For this one of the backend you could use the Google Places autocomplete API (https://developers.google.com/maps/documentation/javascript/examples/places-autocomplete) where they could put in their address. This would help them input it quickly and also make sure it's in a format where you could easily generate the Google Map for it. 

On the front it will display the address along with auto generated Google Map. With all these blocks if the data was formatted for Google's local place structured data (https://developers.google.com/search/docs/data-types/local-business) that would be really handy for the user as well.

**Comment by georgestephanis** [comment]
This may be easiest done via the Maps Block that is shipping in Jetpack -- https://github.com/Automattic/wp-calypso/pull/28498 -- it transitioned away from Google Maps due to API costs and such -- to Mapbox -- https://www.mapbox.com

**Comment by nickhamze** [comment]
That's probably more complex than I was thinking. What about an address block that doesn't have a map or autocomplete but the address is hyperlinked and when you click on it it is opened up in you map app. I bet there is a react component for the input side.

**Comment by georgestephanis** [comment]
That'd be fairly simple -- it's easy to deep link to addresses in google maps and have them open in the app.

**Comment by georgestephanis** [comment]
Address block is created.

I left the `address` field as a freeform textarea, as it would be tricky to handle every instance of how different countries handle stuff.

**Comment by georgestephanis** [comment]
It links to the Google Maps location page for whatever the given address is.
